# Generated by Django 2.2 on 2019-12-20 06:25

from django.db import migrations, models
import django.db.models.deletion
import dream_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('confirm_pw', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('access_level', models.CharField(choices=[(dream_app.models.AccessLevel('Public'), 'Public'), (dream_app.models.AccessLevel('Subscribers'), 'Subscribers'), (dream_app.models.AccessLevel('Private'), 'Private')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to='dream_app.User')),
                ('user_who_like', models.ManyToManyField(related_name='favorite_dreams', to='dream_app.User')),
            ],
        ),
    ]
